spring.application.name=pg

# Server port (optional, default is 8080)
server.port=8080

# PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/pg
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings (important)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Settings
# Secret key needs to be at least 256 bits (32 chars)
app.jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
app.jwt.expiration-ms=86400000